const cfg=window.CAPEX_CONFIG||{};
if(!cfg.supabaseUrl||cfg.supabaseUrl.includes('COLE_AQUI')||!cfg.supabasePublishableKey||cfg.supabasePublishableKey.includes('COLE_AQUI')) document.body.innerHTML='<div style="padding:40px;font-family:Arial"><h2>Configuração pendente</h2><p>Preencha o arquivo <b>config.js</b> com a URL e a chave pública do projeto Supabase.</p></div>';
const sb=window.supabase?.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s), MONTHS=[['jan','Jan'],['fev','Fev'],['mar','Mar'],['abr','Abr'],['mai','Mai'],['jun','Jun'],['jul','Jul'],['ago','Ago'],['set','Set'],['out','Out'],['nov','Nov'],['dez','Dez']];
let state={profile:null,items:[],history:[],users:[],audit:[]}, pendingImport=null, flowChart,typeChart,idleTimer;
let dashboardCategory='obra', dashboardView='prev', activeType='';
const CAPEX_INICIAL=286137351.00, CAPEX_CONTING=39543612.00, CAPEX_RECEBIMENTO=2756634.83, CAPEX_ATUAL=249350373.83;
const CONTING_DETALHE=[['COLETA 14 BIS',800000],['MEDPREV NATAL 1',1243612],['CLÍNICA EUSÉBIO',1100000],['CLÍNICA CAUCAIA',2200000],['NOVA TORRE AMPLIAÇÃO HAPFOR',33000000]];
const RECEB_DETALHE=[['Ampliação de Leitos HS Nossa Senhora do Rosário',641000],['Ampliação de Leitos HS Santana',419000],['Virose Luis França',778000],['FORTALEZA GERAL VIROSE 2026',113000],['MEDPREV Conselheiro Furtado',39947.24],['Amp. de Leitos HS Guarás',540717.96],['Rampa Cirúrgica Hapnatal',213119.63],['Adeq. Qualivida Higienópolis',11850]];
const n=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;let s=String(v??'').trim();if(!s)return 0;s=s.replace(/\s/g,'').replace(/R\$/gi,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');const x=Number(s);return Number.isFinite(x)?x:0}, money=v=>n(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), isAdmin=()=>state.profile?.role==='admin';
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function tipologia(nome=''){const s=nome.toUpperCase();if(s.includes('VISA'))return'Adequação VISA';if(s.includes('PPCI'))return'Adequação PPCI';if(s.includes('TEA'))return'TEA';if(s.includes('COLETA'))return'Coleta';if(s.includes('AMPLIA'))return'Ampliação';if(s.includes('REFORMA'))return'Reforma';if(s.includes('MAN'))return'Manutenção';return'Outros'}
function totalReal(i,m='all'){return m==='all'?MONTHS.reduce((s,[k])=>s+n(i.realizado?.[k]),0):n(i.realizado?.[m])}
function previsto(i){
 const out=Object.fromEntries(MONTHS.map(([k])=>[k,0])), name=String(i.nome||''), real=i.realizado||{};
 if(i.categoria!=='obra') return out;
 if(name.toUpperCase()==='OBRAS NÃO PLANEJADAS') return {...out,...real};
 if(i.contingenciada){MONTHS.forEach(([k])=>out[k]=n(real[k]));return out}
 if(name.includes('CONTING. PARCIAL')&&name.includes('HAPFOR')){MONTHS.forEach(([k])=>out[k]=n(real[k]));const saldo=n(i.capex)-MONTHS.reduce((a,[k])=>a+n(real[k]),0);if(saldo>0)['jul','ago','set','out'].forEach(k=>out[k]=saldo/4);return out}
 if(name.includes('CONTING. PARCIAL')){MONTHS.forEach(([k])=>out[k]=n(real[k]));return out}
 if(name.includes('Novo Hospital Atibaia')){['jan','fev','mar','abr','mai'].forEach(k=>out[k]=n(real[k]));out.jun=Math.max(0,n(i.capex)-['jan','fev','mar','abr','mai'].reduce((a,k)=>a+n(real[k]),0));return out}
 if(name.includes('QUALIVIDA')){out.jul=n(i.capex);return out}
 if(name.includes('TEA Maciel')){MONTHS.forEach(([k])=>out[k]=n(real[k]));return out}
 if(!i.inicio||!i.fim||!n(i.capex))return out;
 const a=new Date(i.inicio+'T12:00:00'),b=new Date(i.fim+'T12:00:00');if(isNaN(a)||isNaN(b))return out;
 if(/Regulatória|Regulatoria|Adequação Regulatória/i.test(name)){MONTHS.forEach(([k])=>out[k]=n(i.capex)/12);return out}
 const rio=name.includes('Novo Hospital Rio de Janeiro'), sinal=rio?.05:.15, execPct=rio?.85:.75;
 const ym=(d)=>d.getFullYear()*12+d.getMonth(), from=ym(a), to=ym(b);
 if(a.getFullYear()===2026)out[MONTHS[a.getMonth()][0]]+=n(i.capex)*sinal;
 const exec=[];for(let x=from+1;x<=to;x++)exec.push(x);
 const mensal=n(i.capex)*execPct/(exec.length||1);
 exec.forEach(x=>{const y=Math.floor(x/12),m=x%12;if(y===2026)out[MONTHS[m][0]]+=mensal});
 [1,2].forEach(z=>{const x=to+z,y=Math.floor(x/12),m=x%12;if(y===2026)out[MONTHS[m][0]]+=n(i.capex)*.05});
 return out
}
function showLogin(msg=''){$('#appShell').hidden=true;$('#loginScreen').hidden=false;$('#loginMessage').textContent=msg;state={profile:null,items:[],history:[],users:[],audit:[]}}
function resetIdle(){clearTimeout(idleTimer);if(!state.profile)return;idleTimer=setTimeout(async()=>{await sb.auth.signOut();showLogin('Sessão encerrada por inatividade.')},Math.max(5,n(cfg.sessionIdleMinutes)||30)*60000)}
['click','keydown','mousemove','touchstart'].forEach(ev=>document.addEventListener(ev,resetIdle,{passive:true}));
async function boot(){if(!sb)return;const {data:{session}}=await sb.auth.getSession();if(!session)return showLogin();const {data:profile,error}=await sb.from('profiles').select('*').eq('id',session.user.id).single();if(error||!profile||!profile.is_active){await sb.auth.signOut();return showLogin('Usuário sem permissão ou bloqueado.')}state.profile=profile;$('#loginScreen').hidden=true;$('#appShell').hidden=false;$('#userIdentity').textContent=profile.full_name||profile.email;$('#roleBadge').textContent=profile.role==='admin'?'Administrador':'Visitante';applyRoleUI();resetIdle();await loadData()}
function applyRoleUI(){document.querySelectorAll('.admin-only').forEach(el=>el.hidden=!isAdmin());if(!isAdmin()&&document.querySelector('.page.active.admin-only'))document.querySelector('[data-page="dashboard"]').click()}
async function loadData(){const [items,history]=await Promise.all([sb.from('capex_items').select('*').is('deleted_at',null).order('nome'),sb.from('import_history').select('*').order('created_at',{ascending:false}).limit(100)]);if(items.error)throw items.error;state.items=items.data||[];state.history=history.data||[];if(isAdmin()){await Promise.all([loadUsers(),loadAudit()])}renderAll()}
async function loadUsers(){const {data,error}=await sb.from('profiles').select('*').order('full_name');if(error)throw error;state.users=data||[]}
async function loadAudit(){const {data,error}=await sb.from('audit_log').select('*').order('created_at',{ascending:false}).limit(300);if(error)throw error;state.audit=data||[]}
function currentItems(){
 const q=$('#search').value.toLowerCase(),m=$('#monthFilter').value;
 return state.items.filter(i=>i.categoria===dashboardCategory&&(!activeType||(i.tipologia||tipologia(i.nome))===activeType)&&(!q||`${i.nome} ${i.ordem}`.toLowerCase().includes(q))&&(m==='all'||totalReal(i,m)>0||n(previsto(i)[m])>0))
}
function renderAll(){applyRoleUI();$('#lastUpdate').textContent='Sincronizado em '+new Date().toLocaleString('pt-BR');renderDashboard();renderHistory();if(isAdmin()){renderManage();renderUsers();renderAudit()}}
function periodMonths(){const m=$('#monthFilter').value;return m==='all'?MONTHS.map(x=>x[0]):[m]}
function openKpi(kind){
 const panel=$('#kpiPanel'),body=$('#kpiPanelBody');$('#kpiPanelTag').textContent='Indicador financeiro';
 if(kind==='conting'){ $('#kpiPanelTitle').textContent='Contingenciamento'; body.innerHTML=`<p>Total acumulado: <b>${money(CAPEX_CONTING)}</b></p>`+CONTING_DETALHE.map(x=>`<div class="detail-row"><span>${esc(x[0])}</span><b>${money(x[1])}</b></div>`).join('')}
 if(kind==='aporte'){ $('#kpiPanelTitle').textContent='Aportes extras'; body.innerHTML=`<p>Total acumulado: <b>${money(CAPEX_RECEBIMENTO)}</b></p>`+RECEB_DETALHE.map(x=>`<div class="detail-row"><span>${esc(x[0])}</span><b>${money(x[1])}</b></div>`).join('')}
 if(kind==='atual'){ $('#kpiPanelTitle').textContent='Composição do CAPEX atual'; body.innerHTML=`<div class="formula-box"><div>CAPEX inicial <b>${money(CAPEX_INICIAL)}</b></div><div>− Contingenciamento <b>${money(CAPEX_CONTING)}</b></div><div>+ Aportes <b>${money(CAPEX_RECEBIMENTO)}</b></div><hr><div>CAPEX atual <b>${money(CAPEX_ATUAL)}</b></div></div>`}
 $('#kpiOverlay').classList.add('open');panel.classList.add('open')
}
function renderDashboard(){
 const items=currentItems(),keys=periodMonths(),isObra=dashboardCategory==='obra';
 const capex=items.reduce((s,i)=>s+n(i.capex),0),real=keys.reduce((s,k)=>s+items.reduce((a,i)=>a+n(i.realizado?.[k]),0),0),prev=keys.reduce((s,k)=>s+items.reduce((a,i)=>a+n(previsto(i)[k]),0),0),saldo=capex-real;
 if(isObra){
  const non=items.filter(i=>String(i.nome).toUpperCase()==='OBRAS NÃO PLANEJADAS'),planned=items.filter(i=>!non.includes(i));
  const realPlan=keys.reduce((s,k)=>s+planned.reduce((a,i)=>a+n(i.realizado?.[k]),0),0),realNon=keys.reduce((s,k)=>s+non.reduce((a,i)=>a+n(i.realizado?.[k]),0),0),total=realPlan+realNon,dev=prev?((total-prev)/prev*100):0;
  const cards=[
   ['CAPEX Inicial',money(CAPEX_INICIAL),`${items.length} obras no portfólio`,''],
   ['Contingenciamento',money(CAPEX_CONTING),'Clique para detalhar','vermelho','conting'],
   ['Aportes Extras',money(CAPEX_RECEBIMENTO),'Clique para detalhar','verde','aporte'],
   ['CAPEX Atual',money(CAPEX_ATUAL),'Clique para detalhar','', 'atual'],
   ['CAPEX Previsto',money(prev),'Modelo 15/75/10 e exceções','verde'],
   ['Realizado Planejado',money(realPlan),`${items.length-non.length} linhas planejadas`,'laranja'],
   ['Realizado Não Planejado',money(realNon),'Linha incluída no planejamento','vermelho'],
   ['Realizado Total',money(total),`${CAPEX_ATUAL?total/CAPEX_ATUAL*100:0}`.replace(/(\.\d\d).*/, '$1')+'% do CAPEX','laranja'],
   ['Desvio Real x Previsto',(dev>=0?'+':'')+dev.toFixed(1)+'%',dev>0?'Acima do previsto':'Abaixo do previsto',Math.abs(dev)>15?'vermelho':Math.abs(dev)>5?'laranja':'verde']
  ];
  $('#kpis').innerHTML=cards.map(c=>`<div class="kpi ${c[3]||''} ${c[4]?'clickable':''}" ${c[4]?`data-kpi="${c[4]}"`:''}><small>${c[0]}</small><strong>${c[1]}</strong><span>${c[2]}</span></div>`).join('');
 } else {
  $('#kpis').innerHTML=[['Cadastros',items.length],['Pacote/Referência',money(capex)],['Realizado',money(real)],['Saldo',money(saldo)]].map(x=>`<div class="kpi"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('')
 }
 document.querySelectorAll('[data-kpi]').forEach(x=>x.onclick=()=>openKpi(x.dataset.kpi));
 const by={};items.forEach(i=>{const t=i.tipologia||tipologia(i.nome);by[t]=(by[t]||0)+(isObra?n(i.capex):totalReal(i))});
 $('#typeCards').innerHTML=Object.entries(by).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<button class="type-card ${activeType===k?'active':''}" data-type="${esc(k)}"><span>${esc(k)}</span><b>${money(v)}</b></button>`).join('');
 document.querySelectorAll('.type-card').forEach(b=>b.onclick=()=>{activeType=activeType===b.dataset.type?'':b.dataset.type;renderDashboard()});
 const labels=MONTHS.map(x=>x[1]),prevData=MONTHS.map(([k])=>items.reduce((s,i)=>s+n(previsto(i)[k]),0)),realData=MONTHS.map(([k])=>items.reduce((s,i)=>s+n(i.realizado?.[k]),0));
 flowChart?.destroy();flowChart=new Chart($('#flowChart'),{type:'line',data:{labels,datasets:[{label:'Previsto',data:prevData},{label:'Realizado',data:realData}]},options:{responsive:true,maintainAspectRatio:false}});
 typeChart?.destroy();typeChart=new Chart($('#typeChart'),{type:'doughnut',data:{labels:Object.keys(by),datasets:[{data:Object.values(by)}]},options:{responsive:true,maintainAspectRatio:false}});
 $('#flowTitle').textContent=isObra?'📈 Fluxo Previsto x Realizado — Obras':'📈 Desembolso mensal — Manutenção';
 $('#typeTitle').textContent=isObra?'🏷️ CAPEX por tipologia':'🏷️ Realizado por tipologia';
 renderFlowTable(items)
}
function renderFlowTable(items){
 const isObra=dashboardCategory==='obra',mkeys=MONTHS.map(x=>x[0]);
 if(!isObra){$('#tableTitle').textContent='📋 Fluxo Realizado por Obra de Manutenção (R$)';$('#tableSubtitle').textContent='Dados da aba OBRAS  MANUTENÇÃO.';$('#dashboardTable').innerHTML='<thead><tr><th>Obra</th><th>Ordem</th>'+MONTHS.map(x=>`<th>${x[1]}</th>`).join('')+'<th>Total</th></tr></thead><tbody>'+items.map(i=>`<tr><td>${esc(i.nome)}</td><td>${esc(i.ordem||'-')}</td>${mkeys.map(k=>`<td class="money">${money(i.realizado?.[k])}</td>`).join('')}<td class="money"><b>${money(totalReal(i))}</b></td></tr>`).join('')+'</tbody>';return}
 $('#tableTitle').textContent='📋 Fluxo Financeiro Mensal por Obra (R$)';$('#tableSubtitle').textContent='15% no início, 75% do mês seguinte ao início até a conclusão e retenções de 5% + 5% nos dois meses posteriores. Exceções do HTML original preservadas.';
 const totalCap=items.reduce((a,i)=>a+n(i.capex),0),tPrev=Object.fromEntries(mkeys.map(k=>[k,items.reduce((a,i)=>a+n(previsto(i)[k]),0)])),tReal=Object.fromEntries(mkeys.map(k=>[k,items.reduce((a,i)=>a+n(i.realizado?.[k]),0)]));
 if(dashboardView==='prev') $('#dashboardTable').innerHTML='<thead><tr><th>Obra</th><th>CAPEX</th>'+MONTHS.map(x=>`<th>Prev ${x[1]}/26</th>`).join('')+'</tr></thead><tbody>'+items.map(i=>`<tr><td>${esc(i.nome)}</td><td class="money">${money(i.capex)}</td>${mkeys.map(k=>`<td class="money">${money(previsto(i)[k])}</td>`).join('')}</tr>`).join('')+`</tbody><tfoot><tr><td>TOTAL PLANEJADO (${items.length} obras)</td><td class="money">${money(totalCap)}</td>${mkeys.map(k=>`<td class="money">${money(tPrev[k])}</td>`).join('')}</tr></tfoot>`;
 else $('#dashboardTable').innerHTML='<thead><tr><th>Obra</th><th>CAPEX</th>'+MONTHS.map(x=>`<th class="real">Real ${x[1]}/26</th><th class="prev">Prev ${x[1]}/26</th>`).join('')+'</tr></thead><tbody>'+items.map(i=>`<tr><td>${esc(i.nome)}</td><td class="money">${money(i.capex)}</td>${mkeys.map(k=>`<td class="money real-cell">${money(i.realizado?.[k])}</td><td class="money">${money(previsto(i)[k])}</td>`).join('')}</tr>`).join('')+`</tbody><tfoot><tr><td>TOTAL</td><td class="money">${money(totalCap)}</td>${mkeys.map(k=>`<td class="money">${money(tReal[k])}</td><td class="money">${money(tPrev[k])}</td>`).join('')}</tr></tfoot>`
}
function renderManage(){const q=$('#manageSearch').value.toLowerCase(),c=$('#manageCategory').value,items=state.items.filter(i=>(c==='all'||i.categoria===c)&&(!q||`${i.nome} ${i.ordem}`.toLowerCase().includes(q)));$('#manageTable').innerHTML='<thead><tr><th>Categoria</th><th>Ordem</th><th>Nome</th><th>CAPEX</th><th>Realizado</th><th>Ações</th></tr></thead><tbody>'+items.map(i=>`<tr><td>${i.categoria==='obra'?'Obra':'Manutenção'}</td><td>${esc(i.ordem)}</td><td>${esc(i.nome)}</td><td class="money">${money(i.capex)}</td><td class="money">${money(totalReal(i))}</td><td><button onclick="editItem('${i.id}')">Editar</button> <button class="danger" onclick="deleteItem('${i.id}')">Excluir</button></td></tr>`).join('')+'</tbody>'}
function openModal(item){if(!isAdmin())return;const f=$('#itemForm'),x=item||{id:'',categoria:'obra',ordem:'',nome:'',inicio:'',fim:'',capex:0,tipologia:'',contingenciada:false,realizado:{}};for(const k of ['id','categoria','ordem','nome','inicio','fim','capex','tipologia'])f.elements[k].value=x[k]||'';f.contingenciada.checked=!!x.contingenciada;MONTHS.forEach(([k])=>f.elements['m_'+k].value=n(x.realizado?.[k]));$('#modalTitle').textContent=x.id?'Editar cadastro':'Novo cadastro';$('#modal').classList.add('open')}
function closeModal(){$('#modal').classList.remove('open')}
window.editItem=id=>openModal(state.items.find(i=>i.id===id));window.deleteItem=async id=>{if(!isAdmin()||!confirm('Excluir este cadastro? Ele permanecerá no histórico de auditoria.'))return;const {error}=await sb.from('capex_items').update({deleted_at:new Date().toISOString(),deleted_by:state.profile.id,updated_by:state.profile.id}).eq('id',id);if(error)return alert(error.message);await loadData()}
function excelDate(v){if(!v)return null;if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);return d?`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`:null}const s=String(v).trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);const m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:null}
function findHeader(rows,needles){return rows.findIndex(row=>needles.every(n=>row.some(v=>String(v).trim().toUpperCase().includes(n))))}
function parseWorkbook(wb){
 const out=[],warnings=[],sheetByName=name=>{const norm=x=>x.replace(/\s+/g,' ').trim().toUpperCase();const key=wb.SheetNames.find(x=>norm(x)===norm(name));return key?wb.Sheets[key]:null};
 const p=sheetByName('PLANEJAMENTO');
 if(p){const a=XLSX.utils.sheet_to_json(p,{header:1,defval:'',raw:true}),h=findHeader(a,['ORDEM INTERNA','NOME OBRA']);if(h<0)warnings.push('Cabeçalho da aba PLANEJAMENTO não encontrado.');else for(let r=h+1;r<a.length;r++){const x=a[r],nome=String(x[1]||'').trim();let ordem=String(x[0]||'').trim();if(!nome)continue;if(nome.toUpperCase()==='OBRAS NÃO PLANEJADAS')ordem='NAO_PLANEJADAS';if(!ordem)continue;out.push({categoria:'obra',ordem,nome,inicio:excelDate(x[2]),fim:excelDate(x[3]),capex:n(x[4]),tipologia:nome.toUpperCase()==='OBRAS NÃO PLANEJADAS'?'Não Planejadas':tipologia(nome),contingenciada:/CONTINGENCIADA/i.test(nome),realizado:Object.fromEntries(MONTHS.map(([k],i)=>[k,n(x[5+i])]))})}}else warnings.push('Aba PLANEJAMENTO não encontrada.');
 const ms=sheetByName('OBRAS MANUTENÇÃO');
 if(ms){const a=XLSX.utils.sheet_to_json(ms,{header:1,defval:'',raw:true}),h=findHeader(a,['ORDEM INTERNA','NOME DA OBRA']);if(h<0)warnings.push('Cabeçalho da aba OBRAS  MANUTENÇÃO não encontrado.');else for(let r=h+1;r<a.length;r++){const x=a[r],nome=String(x[3]||'').trim();let ordem=String(x[2]||'').trim();if(!nome)continue;if(!ordem)ordem='MAN_'+r;out.push({categoria:'manutencao',ordem,nome,inicio:null,fim:null,capex:0,tipologia:'Manutenção',contingenciada:false,realizado:Object.fromEntries(MONTHS.map(([k],i)=>[k,n(x[4+i])]))})}}else warnings.push('Aba OBRAS  MANUTENÇÃO não encontrada.');
 const seen=new Set(),unique=[];for(const x of out){const key=x.categoria+'|'+x.ordem;if(seen.has(key)){warnings.push('Registro duplicado ignorado: '+key);continue}seen.add(key);unique.push(x)}return{rows:unique,warnings}
}
async function sha256(file){const b=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function applyImport(){if(!isAdmin()||!pendingImport?.rows.length)return;$('#applyImport').disabled=true;const file=$('#fileInput').files[0];try{const existing=new Map(state.items.map(x=>[x.categoria+'|'+x.ordem,x]));let created=0,updated=0;for(const x of pendingImport.rows){const old=existing.get(x.categoria+'|'+x.ordem);if(old){const {error}=await sb.from('capex_items').update({...x,updated_by:state.profile.id}).eq('id',old.id);if(error)throw error;updated++}else{const {error}=await sb.from('capex_items').insert({...x,created_by:state.profile.id,updated_by:state.profile.id});if(error)throw error;created++}}const hash=file?await sha256(file):null;const {error:hErr}=await sb.from('import_history').insert({file_name:file?.name||'planilha.xlsx',file_size:file?.size||null,file_hash:hash,total_records:pendingImport.rows.length,created_records:created,updated_records:updated,ignored_records:pendingImport.warnings.length,imported_by:state.profile.id,status:'completed'});if(hErr)throw hErr;$('#importPreview').innerHTML=`Importação concluída.<br><b>${created}</b> criados · <b>${updated}</b> atualizados.`;pendingImport=null;await loadData()}catch(e){alert('Falha na importação: '+e.message)}finally{$('#applyImport').disabled=!pendingImport?.rows.length}}
function renderHistory(){$('#history').innerHTML=state.history.length?'<table><thead><tr><th>Data</th><th>Arquivo</th><th>Criados</th><th>Atualizados</th><th>Ignorados</th></tr></thead><tbody>'+state.history.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString('pt-BR')}</td><td>${esc(x.file_name)}</td><td>${x.created_records}</td><td>${x.updated_records}</td><td>${x.ignored_records||0}</td></tr>`).join('')+'</tbody></table>':'Nenhuma importação realizada.'}
function renderUsers(){$('#usersTable').innerHTML='<thead><tr><th>Nome/e-mail</th><th>Perfil</th><th>Status</th><th>Ações</th></tr></thead><tbody>'+state.users.map(u=>`<tr><td>${esc(u.full_name||'-')}<br><small>${esc(u.email)}</small></td><td>${u.role==='admin'?'Administrador':'Visitante'}</td><td class="${u.is_active?'status-active':'status-disabled'}">${u.is_active?'Ativo':'Bloqueado'}</td><td>${u.id===state.profile.id?'Usuário atual':`<button onclick="toggleUser('${u.id}',${!u.is_active})">${u.is_active?'Bloquear':'Ativar'}</button> <button onclick="changeRole('${u.id}','${u.role==='admin'?'viewer':'admin'}')">Tornar ${u.role==='admin'?'visitante':'admin'}</button> <button onclick="resetPassword('${u.id}')">Nova senha</button>`}</td></tr>`).join('')+'</tbody>'}
function renderAudit(){$('#auditTable').innerHTML='<thead><tr><th>Data</th><th>Usuário</th><th>Ação</th><th>Registro</th><th>Resumo</th></tr></thead><tbody>'+state.audit.map(a=>`<tr><td>${new Date(a.created_at).toLocaleString('pt-BR')}</td><td>${esc(a.actor_email||a.actor_id||'-')}</td><td>${esc(a.operation)}</td><td>${esc(a.record_id||'-')}</td><td class="audit-json" title="${esc(JSON.stringify(a.new_data||a.old_data||{}))}">${esc((a.new_data||a.old_data||{}).nome||JSON.stringify(a.new_data||a.old_data||{}))}</td></tr>`).join('')+'</tbody>'}
async function invokeUserAdmin(payload){const {data,error}=await sb.functions.invoke(cfg.edgeFunctionName,{body:payload});if(error){let message=error.message||'Falha ao chamar a função';try{const body=await error.context?.json();if(body?.error)message=body.error}catch{}throw new Error(message)}if(data?.error)throw new Error(data.error);return data}
window.toggleUser=async(id,is_active)=>{try{await invokeUserAdmin({action:'set_active',user_id:id,is_active});await loadData()}catch(e){alert(e.message)}};window.changeRole=async(id,role)=>{if(!confirm('Confirmar alteração de perfil?'))return;try{await invokeUserAdmin({action:'set_role',user_id:id,role});await loadData()}catch(e){alert(e.message)}};window.resetPassword=async id=>{const password=prompt('Digite uma senha temporária com pelo menos 12 caracteres:');if(!password)return;try{await invokeUserAdmin({action:'reset_password',user_id:id,password});alert('Senha redefinida. Envie-a por canal seguro.')}catch(e){alert(e.message)}};
MONTHS.forEach(([k,l])=>{$('#monthFilter').insertAdjacentHTML('beforeend',`<option value="${k}">${l}</option>`);$('#monthInputs').insertAdjacentHTML('beforeend',`<label>${l}<input name="m_${k}" type="number" step="0.01" min="0"></label>`)})
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{if(b.hidden)return;document.querySelectorAll('.nav,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.page).classList.add('active')});$('#monthFilter').onchange=renderDashboard;$('#search').oninput=renderDashboard;
document.querySelectorAll('.module-tab').forEach(b=>b.onclick=()=>{dashboardCategory=b.dataset.category;activeType='';document.querySelectorAll('.module-tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.table-tabs').forEach(x=>x.hidden=dashboardCategory!=='obra');renderDashboard()});
document.querySelectorAll('.table-tab').forEach(b=>b.onclick=()=>{dashboardView=b.dataset.view;document.querySelectorAll('.table-tab').forEach(x=>x.classList.toggle('active',x===b));renderDashboard()});
$('#clearDashboardFilters').onclick=()=>{$('#search').value='';$('#monthFilter').value='all';activeType='';renderDashboard()};
$('#closeKpiPanel').onclick=$('#kpiOverlay').onclick=()=>{$('#kpiPanel').classList.remove('open');$('#kpiOverlay').classList.remove('open')};$('#manageSearch').oninput=renderManage;$('#manageCategory').onchange=renderManage;$('#newBtn').onclick=()=>openModal();$('#closeModal').onclick=$('#cancelModal').onclick=closeModal;
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginMessage').textContent='Entrando...';const f=e.currentTarget,{error}=await sb.auth.signInWithPassword({email:f.email.value.trim(),password:f.password.value});if(error)return $('#loginMessage').textContent='E-mail ou senha inválidos.';await boot()};$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();showLogin()};
$('#itemForm').onsubmit=async e=>{e.preventDefault();if(!isAdmin())return;const f=e.currentTarget,item={categoria:f.categoria.value,ordem:f.ordem.value.trim(),nome:f.nome.value.trim(),inicio:f.inicio.value||null,fim:f.fim.value||null,capex:n(f.capex.value),tipologia:f.tipologia.value.trim()||tipologia(f.nome.value),contingenciada:f.contingenciada.checked,realizado:Object.fromEntries(MONTHS.map(([k])=>[k,n(f.elements['m_'+k].value)])),updated_by:state.profile.id};const id=f.id.value;const q=id?sb.from('capex_items').update(item).eq('id',id):sb.from('capex_items').insert({...item,created_by:state.profile.id});const {error}=await q;if(error)return alert(error.message);closeModal();await loadData()};
$('#fileInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});pendingImport=parseWorkbook(wb);$('#importPreview').innerHTML=`Arquivo: <b>${esc(file.name)}</b><br><b>${pendingImport.rows.length}</b> registros reconhecidos.`+(pendingImport.warnings.length?`<div class="warning">${pendingImport.warnings.slice(0,10).map(esc).join('<br>')}</div>`:'');$('#applyImport').disabled=!pendingImport.rows.length}catch(e){pendingImport=null;$('#importPreview').textContent='Não foi possível ler a planilha: '+e.message}};$('#applyImport').onclick=applyImport;
$('#newUserBtn').onclick=()=>$('#userModal').classList.add('open');$('#closeUserModal').onclick=$('#cancelUserModal').onclick=()=>$('#userModal').classList.remove('open');$('#userForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await invokeUserAdmin({action:'create',email:f.email.value.trim(),password:f.password.value,full_name:f.full_name.value.trim(),role:f.role.value});f.reset();$('#userModal').classList.remove('open');await loadData()}catch(err){alert(err.message)}};
sb?.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')showLogin()});boot();
